//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Hamza_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedJobDetail
    {
        public int Id { get; set; }
        public Nullable<int> FormNo { get; set; }
        public string Company { get; set; }
        public string Measure { get; set; }
        public string Inspection { get; set; }
        public string Month { get; set; }
        public string Status { get; set; }
    }
}
