
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ERP_Hamza_API.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FunderQuery
{

    public int Id { get; set; }

    public Nullable<int> FormNo { get; set; }

    public string FunderName { get; set; }

    public string FunderText { get; set; }

    public string Status { get; set; }

    public string MemberType { get; set; }

    public string Member { get; set; }

    public string MTime { get; set; }

    public string MDate { get; set; }

}

}
