
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ERP_Hamza_API.Models
{

using System;
    using System.Collections.Generic;
    
public partial class JobForm1
{

    public int Id { get; set; }

    public string RefNo { get; set; }

    public string LeadGenerator { get; set; }

    public string Scheme { get; set; }

    public string Surname { get; set; }

    public string Forename { get; set; }

    public string DOB { get; set; }

    public string PropertyNo { get; set; }

    public string AddressLine1 { get; set; }

    public string Town { get; set; }

    public string Postcode { get; set; }

    public string SurveyName { get; set; }

    public string SurveyDate { get; set; }

    public string SurveyTime { get; set; }

    public string Tenure { get; set; }

    public Nullable<int> Status { get; set; }

    public string CreateBy { get; set; }

    public Nullable<System.DateTime> CDate { get; set; }

    public string PassInstaName { get; set; }

    public Nullable<System.DateTime> PassInstaDate { get; set; }

    public string PassInstaTime { get; set; }

    public string LoftName { get; set; }

    public Nullable<System.DateTime> LoftDate { get; set; }

    public string LoftTime { get; set; }

    public string RIRName { get; set; }

    public Nullable<System.DateTime> RIRDate { get; set; }

    public string RIRTime { get; set; }

    public string EWIName { get; set; }

    public Nullable<System.DateTime> EWIDate { get; set; }

    public string EWITime { get; set; }

    public string IWIName { get; set; }

    public Nullable<System.DateTime> IWIDate { get; set; }

    public string IWITime { get; set; }

    public string BoilerName { get; set; }

    public Nullable<System.DateTime> BoilerDate { get; set; }

    public string BoilerTime { get; set; }

    public string HCName { get; set; }

    public Nullable<System.DateTime> HCDate { get; set; }

    public string HCTime { get; set; }

    public string SolarName { get; set; }

    public Nullable<System.DateTime> SolarDate { get; set; }

    public string SolarTime { get; set; }

    public string AshipName { get; set; }

    public Nullable<System.DateTime> AshipDate { get; set; }

    public string AshipTime { get; set; }

    public string FunderName { get; set; }

    public Nullable<System.DateTime> FunderDate { get; set; }

    public string FunderQText { get; set; }

    public string FunderTime { get; set; }

    public string FunderName2 { get; set; }

    public string IpadQAccessorName { get; set; }

    public string IpadQAccessorNameRcInst { get; set; }

    public string EprReportText { get; set; }

    public string EprJobContrbText { get; set; }

    public string RcInstructSideNote { get; set; }

    public string RcInstructSideDate { get; set; }

    public string JobNote { get; set; }

    public string Email { get; set; }

    public string ContactNo { get; set; }

    public Nullable<bool> ChkL1 { get; set; }

    public Nullable<bool> ChkL2 { get; set; }

    public Nullable<bool> ChkL3 { get; set; }

    public Nullable<bool> ChkL4 { get; set; }

    public Nullable<bool> ChkL5 { get; set; }

    public Nullable<bool> ChkL6 { get; set; }

    public Nullable<bool> ChkL7 { get; set; }

    public Nullable<bool> ChkL8 { get; set; }

    public Nullable<bool> IsGDGC { get; set; }

    public Nullable<bool> isPostStateReq { get; set; }

    public Nullable<bool> isLogemnt { get; set; }

    public string JobType { get; set; }

}

}
