//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Hamza_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERP_DBEntities : DbContext
    {
        public ERP_DBEntities()
            : base("name=ERP_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<FormStatu> FormStatus { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<FunderQuery> FunderQueries { get; set; }
        public virtual DbSet<CheckListData> CheckListDatas { get; set; }
        public virtual DbSet<CheckListNameList> CheckListNameLists { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<PagesPermission> PagesPermissions { get; set; }
        public virtual DbSet<TrackRCInstState> TrackRCInstStates { get; set; }
        public virtual DbSet<PostStateReqData> PostStateReqDatas { get; set; }
        public virtual DbSet<TMQuery> TMQueries { get; set; }
        public virtual DbSet<JobForm1> JobForm1 { get; set; }
        public virtual DbSet<AssignedJobDetail> AssignedJobDetails { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
    }
}
