
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ERP_Hamza_API.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TMQuery
{

    public int Id { get; set; }

    public Nullable<int> FormNo { get; set; }

    public string TextA { get; set; }

    public string TextB { get; set; }

    public string Status { get; set; }

}

}
